import type { Meta, StoryObj } from "@storybook/web-components";
import { html } from "lit";
import { chromaticModes } from "../../../.storybook/modes";
import type { QGDSTable } from "./qgds-table";
import "./qgds-table";

interface Args {
  responsive: QGDSTable["responsive"];
  "is-striped": boolean;
  "is-hovered": boolean;
  "has-border": boolean;
  "has-sticky-header": boolean;
  // Auto-discovered CEM property keys — included so argTypes can disable them.
  hasBorder?: boolean;
  hasStickyHeader?: boolean;
  isHovered?: boolean;
  isStriped?: boolean;
  _handleKeyDown?: unknown;
  _onSlotChange?: unknown;
}

type Story = StoryObj<Args>;

// ── Shared sample content ─────────────────────────────────────────────────────

const sampleRows = html`
  <tr>
    <td>Cell item 01</td>
    <td>Cell item 02</td>
    <td>Cell item 03</td>
  </tr>
  <tr>
    <td>Cell item 04</td>
    <td>Cell item 05</td>
    <td>Cell item 06</td>
  </tr>
  <tr>
    <td>Cell item 07</td>
    <td>Cell item 08</td>
    <td>Cell item 09</td>
  </tr>
  <tr>
    <td>Cell item 10</td>
    <td>Cell item 11</td>
    <td>Cell item 12</td>
  </tr>
  <tr>
    <td>Cell item 13</td>
    <td>Cell item 14</td>
    <td>Cell item 15</td>
  </tr>
`;

const sampleTable = html`
  <table>
    <caption>
      Table caption
      <span class="caption-subtitle">Table is ordered by</span>
    </caption>
    <thead>
      <tr>
        <th scope="col">Header 1</th>
        <th scope="col">Header 2</th>
        <th scope="col">Header 3</th>
      </tr>
    </thead>
    <tbody>
      ${sampleRows}
    </tbody>
    <tfoot>
      <tr>
        <td>Footer 1</td>
        <td>Footer 2</td>
        <td>Footer 3</td>
      </tr>
    </tfoot>
  </table>
`;

const meta: Meta<Args> = {
  title: "Components/Table",
  component: "qgds-table",
  tags: ["autodocs"],
  args: {
    responsive: "scroll",
    "is-striped": false,
    "is-hovered": false,
    "has-border": false,
    "has-sticky-header": false,
  },
  argTypes: {
    responsive: {
      control: "select",
      options: ["scroll", "stack"],
      description:
        'Responsive behaviour: `"scroll"` wraps the table in a horizontally scrollable container; `"stack"` stacks cells on small screens with visible header labels.',
      table: { defaultValue: { summary: "scroll" } },
    },
    "is-striped": {
      control: "boolean",
      description: "Applies alternating (banded) row shading.",
      table: { defaultValue: { summary: "false" } },
    },
    "is-hovered": {
      control: "boolean",
      description: "Highlights table rows on mouse hover.",
      table: { defaultValue: { summary: "false" } },
    },
    "has-border": {
      control: "boolean",
      description: "Renders a visible border around the outer scroll/wrapper container.",
      table: { defaultValue: { summary: "false" } },
    },
    "has-sticky-header": {
      control: "boolean",
      description: "Sticks `<thead>` to the top of the scroll container during vertical scroll.",
      table: { defaultValue: { summary: "false" } },
    },
    // Disable duplicate JS-property controls auto-generated by Storybook from the CEM members list.
    hasBorder: { table: { disable: true } },
    hasStickyHeader: { table: { disable: true } },
    isHovered: { table: { disable: true } },
    isStriped: { table: { disable: true } },
    // Hide internal methods surfaced by the CEM.
    _handleKeyDown: { table: { disable: true } },
    _onSlotChange: { table: { disable: true } },
  },
  render: (args) => html`
    <qgds-table
      responsive=${args.responsive}
      ?is-striped=${args["is-striped"]}
      ?is-hovered=${args["is-hovered"]}
      ?has-border=${args["has-border"]}
      ?has-sticky-header=${args["has-sticky-header"]}
    >
      ${sampleTable}
    </qgds-table>
  `,
};

export default meta;

// ── Stories ───────────────────────────────────────────────────────────────────

/**
 * Default configuration — a horizontally scrollable wrapper with no
 * additional decoration. The native `<table>` is passed in unchanged.
 */
export const Default: Story = {
  name: "Borderless",
  args: { responsive: "scroll" },
  parameters: { ...chromaticModes },
};

/**
 * A bordered container draws a clear boundary around the table. Pairs
 * well with `is-striped` for dense data tables.
 */
export const Bordered: Story = {
  name: "Bordered (Default)",
  args: { responsive: "scroll", "has-border": true },
  parameters: { ...chromaticModes },
};

/**
 * Striped (banded) rows aid readability for data-heavy tables by
 * differentiating alternate rows visually.
 */
export const Striped: Story = {
  name: "Striped / Banded",
  args: { responsive: "scroll", "has-border": true, "is-striped": true },
  parameters: { ...chromaticModes },
};

/**
 * Row hover highlights the row under the cursor, helping users track
 * which row they are reading in wide tables.
 */
// export const Hovered: Story = {
//   name: "Row Hover",
//   args: { responsive: "scroll", "has-border": true, "is-hovered": true },
//   parameters: { ...chromaticModes },
// };

/**
 * The sticky header keeps `<thead>` visible as the user scrolls vertically
 * through a long table. A `max-height` is automatically applied to the
 * scroll container (640 px mobile / 1000 px desktop).
 */
export const StickyHeader: Story = {
  name: "Sticky Header",
  args: { responsive: "scroll", "has-border": true, "is-striped": true, "has-sticky-header": true },
  render: (args) => html`
    <qgds-table
      responsive="${args.responsive}"
      ?is-striped=${args["is-striped"]}
      ?has-border=${args["has-border"]}
      ?has-sticky-header=${args["has-sticky-header"]}
    >
      <table>
        <caption>
          Table caption
          <span class="caption-subtitle">Scrolls vertically with sticky header</span>
        </caption>
        <thead>
          <tr>
            <th scope="col">Header</th>
            <th scope="col">Header</th>
            <th scope="col">Header</th>
            <th scope="col">Header</th>
          </tr>
        </thead>
        <tbody>
          ${Array.from(
            { length: 20 },
            (_, i) => html`
              <tr>
                <td>Row ${i + 1} — Cell A</td>
                <td>Cell 1</td>
                <td>Cell 2</td>
                <td>Cell 3</td>
              </tr>
            `
          )}
        </tbody>
        <tfoot>
          <tr>
            <td>Footer</td>
            <td>Footer</td>
            <td>Footer</td>
            <td>Footer</td>
          </tr>
        </tfoot>
      </table>
    </qgds-table>
  `,
  parameters: { ...chromaticModes },
};

/**
 * Stack mode renders the table normally on desktop. On viewports narrower
 * than 768 px, `<thead>` is visually hidden and each `<td>` displays its
 * corresponding column header as a label — populated automatically by the
 * component from the first `<thead tr>` row.
 */
export const Stack: Story = {
  name: "Responsive Stack",
  args: { responsive: "stack", "has-border": true },
  parameters: { ...chromaticModes },
};

/**
 * All boolean modifiers enabled together — bordered, striped, hover and
 * sticky header — for a fully featured table.
 */
export const AllModifiers: Story = {
  name: "All Modifiers",
  args: {
    responsive: "scroll",
    "has-border": true,
    "is-striped": true,
    "is-hovered": true,
    "has-sticky-header": true,
  },
  render: (args) => html`
    <qgds-table
      responsive="${args.responsive}"
      ?is-striped=${args["is-striped"]}
      ?is-hovered=${args["is-hovered"]}
      ?has-border=${args["has-border"]}
      ?has-sticky-header=${args["has-sticky-header"]}
    >
      <table>
        <caption>
          Table caption
          <span class="caption-subtitle">Bordered · Striped · Hover · Sticky header</span>
        </caption>
        <thead>
          <tr>
            <th scope="col">Header 1</th>
            <th scope="col">Header 2</th>
            <th scope="col">Header 3</th>
            <th scope="col">Header 4</th>
          </tr>
        </thead>
        <tbody>
          ${Array.from(
            { length: 15 },
            (_, i) => html`
              <tr>
                <td>Row ${i + 1} — Cell A</td>
                <td>Cell</td>
                <td>Cell</td>
                <td>Cell</td>
              </tr>
            `
          )}
        </tbody>
        <tfoot>
          <tr>
            <td>Footer</td>
            <td>Footer</td>
            <td>Footer</td>
            <td>Footer</td>
          </tr>
        </tfoot>
      </table>
    </qgds-table>
  `,
  parameters: { ...chromaticModes },
};

/**
 * Tables with multiple header levels use `colspan`, `rowspan`, and the
 * `cell-left-border`, `cell--middle`, and `cell--numeric` utility classes
 * to group and align columns. These classes are authored on the `<th>` / `<td>`
 * elements directly and are not injected by the component.
 */
export const MultilevelHeadings: Story = {
  name: "Multilevel Headings",
  args: { responsive: "scroll", "has-border": true, "is-striped": true, "is-hovered": true },
  render: (args) => html`
    <qgds-table
      responsive="${args.responsive}"
      ?has-border=${args["has-border"]}
      ?is-striped=${args["is-striped"]}
      is-hovered=${args["is-hovered"]}
    >
      <table>
        <caption>
          Table caption
          <span class="caption-subtitle">Table is ordered by</span>
        </caption>
        <thead>
          <tr>
            <th rowspan="2" scope="col">Header</th>
            <th colspan="3" class="cell-left-border cell--middle" scope="colgroup">Header group</th>
          </tr>
          <tr>
            <th scope="col" class="cell-left-border">Sub-header</th>
            <th scope="col" class="cell-left-border">Sub-header</th>
            <th scope="col" class="cell-left-border cell--numeric">Number %</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Cell</td>
            <td>Cell</td>
            <td>Cell</td>
            <td class="cell--numeric">5</td>
          </tr>
          <tr>
            <td>Cell</td>
            <td>Cell</td>
            <td>Cell</td>
            <td class="cell--numeric">10</td>
          </tr>
          <tr>
            <td>Cell</td>
            <td>Cell</td>
            <td>Cell</td>
            <td class="cell--numeric">15</td>
          </tr>
          <tr>
            <td>Cell</td>
            <td>Cell</td>
            <td>Cell</td>
            <td class="cell--numeric">20</td>
          </tr>
          <tr>
            <td>Cell</td>
            <td>Cell</td>
            <td>Cell</td>
            <td class="cell--numeric">25</td>
          </tr>
        </tbody>
        <tfoot>
          <tr>
            <td>Footer</td>
            <td>Footer</td>
            <td>Footer</td>
            <td class="cell--numeric">75</td>
          </tr>
        </tfoot>
      </table>
    </qgds-table>
  `,
  parameters: { ...chromaticModes },
};

/**
 * Custom column widths are set via `header--width-{n}` utility classes on
 * `<th>` elements, authored directly in the markup. The component does not
 * inject or alter these classes.
 *
 * Available widths: 10, 15, 20, 25, 33, 40, 50, 75 (percentage).
 */
export const CustomWidths: Story = {
  name: "Custom Widths",
  args: { responsive: "scroll", "has-border": true },
  render: (args) => html`
    <qgds-table responsive="${args.responsive}" ?has-border=${args["has-border"]}>
      <table>
        <caption>
          Table caption
          <span class="caption-subtitle">Table is ordered by</span>
        </caption>
        <thead>
          <tr>
            <th scope="col" class="header--width-10">ID</th>
            <th scope="col">Name</th>
            <th scope="col" class="header--width-50">Description</th>
          </tr>
        </thead>
        <tbody>
          ${sampleRows} ${sampleRows}
        </tbody>
        <tfoot>
          <tr>
            <td>Footer</td>
            <td>Footer</td>
            <td>Footer</td>
          </tr>
        </tfoot>
      </table>
    </qgds-table>
  `,
  parameters: { ...chromaticModes },
};
